# Generated by Django 5.2.16 on 2026-07-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('label', models.CharField(blank=True, help_text="Optional note, e.g. 'HR', 'Owner', 'Sales Lead' — for admin reference only.", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop sending contact form notifications to this address without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Notification Recipient',
                'verbose_name_plural': 'Contact Notification Recipients',
                'ordering': ['email'],
            },
        ),
    ]
