# Generated by Django 5.2.16 on 2026-07-13 19:07

import apps.videos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'm4v']), apps.videos.validators.VideoMimeTypeValidator()])),
                ('thumbnail', models.ImageField(blank=True, help_text='Used as the video poster and for email/link previews. Upload manually — email clients cannot embed video.', null=True, upload_to='videos/thumbnails/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video asset',
                'verbose_name_plural': 'Video assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='videos_vide_slug_192b3b_idx'), models.Index(fields=['is_published', '-created_at'], name='videos_vide_is_publ_ec3cfb_idx')],
            },
        ),
    ]
