# Generated by Django 5.2.16 on 2026-07-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal label for admin lists — not shown on the public site.', max_length=200)),
                ('alt_text', models.CharField(help_text='Accessible description rendered as the image alt attribute.', max_length=255)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_published', 'sort_order'], name='public_hero_is_publ_ca7f01_idx')],
            },
        ),
    ]
