# Generated by Django 5.2.16 on 2026-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_code', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(editable=False, max_length=128)),
                ('contact_email', models.EmailField(help_text='Where password-reset / provisioning links are sent. Not used as a login field.', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to block portal login without deleting the account.')),
                ('failed_attempts', models.PositiveIntegerField(default=0, editable=False)),
                ('locked_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_login', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier Portal Account',
                'verbose_name_plural': 'Supplier Portal Accounts',
                'ordering': ['cage_code'],
            },
        ),
    ]
