# Generated by Django 5.2.16 on 2026-07-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierportalaccount',
            name='last_reset_request_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
